-i ../../data/robots.edge -if ../../constructing_index/construct_pathindex/index/robots_2_path -o test -qw ../../workload/query_fulllabel4k2 -k 2
-i ../../data/robots.edge -if ../../constructing_index/construct_wapathindex/index/robots_2_wa_path -o test_wa -qw ../../workload/query_fulllabel4k2 -iw ../../workload/query_fulllabel4k2 -k 2
